[phase.setup]
  aptPkgs = ['...', 'libreoffice', 'unoconv']
  nixPkgs = ['...', 'libreoffice', 'unoconv']
  
[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
