[phase.setup]
  aptPkgs = ['...', 'libreoffice', 'gir1.2-gtk-3.0']
  nixPkgs = ['...', 'libreoffice']
  commands = [
  "apt-get update",
  "apt-get install -y libreoffice",
  "sudo apt-get install -y libcairo2-dev libpango1.0-dev libgdk-pixbuf2.0-dev libffi-dev shared-mime-info"

]
cmds = ['apt-get update && apt-get install -y libreoffice libcairo2-dev libpango1.0-dev libgdk-pixbuf2.0-dev libffi-dev shared-mime-info']

[build]
builder = "NIXPACKS"
# Install dependencies
cmds = ['apt-get update && apt-get install -y libreoffice libcairo2-dev libpango1.0-dev libgdk-pixbuf2.0-dev libffi-dev shared-mime-info']



[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
  internal_port = 6302
  protocol = "http"
  command = "sudo apt-get install -y libcairo2-dev libpango1.0-dev libgdk-pixbuf2.0-dev libffi-dev shared-mime-info"
cmds = ['apt-get update && apt-get install -y libreoffice libcairo2-dev libpango1.0-dev libgdk-pixbuf2.0-dev libffi-dev shared-mime-info']
