[phase.setup]
  aptPkgs = ['...', 'libreoffice']
  aptPkgs = ["...", "libreoffice"]
  nixPkgs = ["...", "libreoffice"]
  nixPkgs = ['...', 'libreoffice']
  
[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
