[phase.setup]
  aptPkgs = ['...', 'libreoffice', 'gir1.2-gtk-3.0']
  nixPkgs = ['...', 'libreoffice']
  commands = [
  "apt-get update",
  "apt-get install -y libreoffice",
  "apt install python3-pip python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0"
]
  
[build]
builder = "NIXPACKS"
# Install dependencies
command = "apt-get update && apt-get install -y libreoffice python3-pip python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0"



[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
  internal_port = 6302
  protocol = "http"
  command = "apt install python3-pip python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0"
