[phase.setup]
  aptPkgs = ['sudo apt-get update && sudo apt-get install libreoffice']
  nixPkgs = ['libreoffice']
  
[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
